/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './pages/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
    './app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        // Material Design 3 — MediKiosk Green Theme (Light Mode)
        'surface-tint': '#3b6934',
        'secondary-container': '#d9e6da',
        'surface-bright': '#fbf9f8',
        'error': '#ba1a1a',
        'on-primary': '#ffffff',
        'tertiary-container': '#50513f',
        'primary-container': '#2d5a27',
        'tertiary-fixed-dim': '#c8c8b0',
        'surface-container-high': '#eae8e7',
        'on-primary-container': '#9dd090',
        'secondary-fixed': '#d9e6da',
        'outline-variant': '#c2c9bb',
        'on-primary-fixed': '#002201',
        'surface-dim': '#dbd9d9',
        'inverse-on-surface': '#f2f0f0',
        'surface-container': '#efeded',
        'primary': '#154212',
        'background': '#fbf9f8',
        'on-secondary-fixed': '#131e17',
        'primary-fixed-dim': '#a1d494',
        'inverse-surface': '#303030',
        'on-secondary': '#ffffff',
        'secondary-fixed-dim': '#bdcabe',
        'on-surface': '#1b1c1c',
        'surface-container-lowest': '#ffffff',
        'primary-fixed': '#bcf0ae',
        'outline': '#72796e',
        'on-surface-variant': '#42493e',
        'on-tertiary-fixed': '#1b1d0e',
        'on-tertiary': '#ffffff',
        'surface-variant': '#e4e2e2',
        'secondary': '#556158',
        'inverse-primary': '#a1d494',
        'on-tertiary-fixed-variant': '#474836',
        'surface-container-low': '#f5f3f3',
        'surface-container-highest': '#e4e2e2',
        'on-secondary-container': '#5b675e',
        'error-container': '#ffdad6',
        'surface': '#fbf9f8',
        'on-error-container': '#93000a',
        'on-primary-fixed-variant': '#23501e',
        'on-error': '#ffffff',
        'on-tertiary-container': '#c3c4ac',
        'tertiary-fixed': '#e4e4cc',
        'on-secondary-fixed-variant': '#3e4a41',
        'on-background': '#1b1c1c',
        'tertiary': '#393a29',
      },
      borderRadius: {
        'DEFAULT': '1rem',
        'lg': '2rem',
        'xl': '3rem',
        'full': '9999px',
      },
      spacing: {
        'base': '8px',
        'unit-1': '0.5rem',
        'unit-2': '1rem',
        'unit-3': '1.5rem',
        'unit-4': '2rem',
        'unit-6': '3rem',
        'gutter': '16px',
        'container-margin': '24px',
      },
      fontFamily: {
        'display': ['Quicksand', 'sans-serif'],
        'body': ['Public Sans', 'sans-serif'],
        'sans': ['Public Sans', 'sans-serif'],
      },
      fontSize: {
        'display-lg': ['40px', { lineHeight: '48px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'display-lg-mobile': ['32px', { lineHeight: '40px', fontWeight: '700' }],
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'label-sm': ['14px', { lineHeight: '20px', letterSpacing: '0.01em', fontWeight: '600' }],
      },
      boxShadow: {
        'neo': '8px 8px 16px #dbd9d9, -8px -8px 16px #ffffff',
        'neo-sm': '4px 4px 8px #dbd9d9, -4px -4px 8px #ffffff',
        'neo-lg': '12px 12px 24px rgba(209,207,206,0.4), -12px -12px 24px rgba(255,255,255,0.8)',
        'neo-inner': 'inset 8px 8px 16px #dbd9d9, inset -8px -8px 16px #ffffff',
        'neo-inner-sm': 'inset 4px 4px 8px #dbd9d9, inset -4px -4px 8px #ffffff',
        'glow-green': '0 0 25px -5px rgba(21, 66, 18, 0.3)',
        'glow-red': '0 0 25px -5px rgba(186, 26, 26, 0.4)',
      },
      animation: {
        'pulse-red': 'pulse-red 2s infinite',
        'fade-in': 'fade-in 0.3s ease-out',
        'slide-up': 'slide-up 0.4s ease-out',
      },
      keyframes: {
        'pulse-red': {
          '0%': { transform: 'scale(1)', boxShadow: '0 0 0 0 rgba(186,26,26,0.4)' },
          '70%': { transform: 'scale(1.02)', boxShadow: '0 0 0 15px rgba(186,26,26,0)' },
          '100%': { transform: 'scale(1)', boxShadow: '0 0 0 0 rgba(186,26,26,0)' },
        },
        'fade-in': {
          '0%': { opacity: '0', transform: 'translateY(8px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        'slide-up': {
          '0%': { opacity: '0', transform: 'translateY(20px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
      },
    },
  },
  plugins: [],
}
